SELECT
    l.REGION,
    SUM(f.SALE_AMOUNT) AS total_sales,
    ROUND(
        SUM(f.SALE_AMOUNT) * 100.0
        / SUM(SUM(f.SALE_AMOUNT)) OVER (),
    2) AS pct_of_total
FROM MEAT_SALE_F f
JOIN LOCATION_D l ON f.LOCATION_ID = l.LOCATION_ID
JOIN DATE_D d     ON f.SALE_DATE   = d.DATE_ID
WHERE d.YEAR = EXTRACT(YEAR FROM SYSDATE)
GROUP BY l.REGION
ORDER BY total_sales DESC
FETCH FIRST 3 ROWS ONLY;